HealthCareJC/Models/EventAd.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Policy;
using System.Web;

namespace HealthCareJC.Models
{
    public class EventAd
    {
        public int Id { get; set; }
        public string EventNumber { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EventDate { get; set; }
        public string time { get; set; }
        public int EventCategoryId { get; set; }  //Family Event, Wedding, Marriage, BirthDay
        public string Address { get; set; } //google API
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string UserId { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public bool status { get; set; }
        public string Website { get; set; }
        public decimal? EventAmount { get; set; }
        //public Decimal EventAmout { get; set; }
        [ForeignKey("EventCategoryId")]
        public virtual EventCategory eventCatrgory { get; set; }
        [ForeignKey("UserId")]
        public virtual ApplicationUser User { get; set; }
        public int isPaid { get; set; }
             
       
       
    }
}

HealthCareJC/ViewModels/ManageEventsViewModel.cs
using HealthCareJC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HealthCareJC.ViewModels
{
    public class ManageEventsViewModel
    {
        public List<EventAd> eventads { get; set; }

    }
}

HealthCareJC/Controllers/EventAdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthCareJC.Models;
using Microsoft.AspNet.Identity;
using HealthCareJC.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using HealthCareJC.Services;

namespace HealthCareJC.Controllers
{
    public class EventAdsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private JCEmailService jcemail = new JCEmailService();
        // GET: EventAds
       public ActionResult EventDetail(int eventId)
        {
            var model = new EventAdViewsModel
            {
                eventlist = (from emp in db.Employers
                           join events in db.EventAds
                            on emp.UserId equals events.UserId

                           where events.Id== eventId


                             select new
                           {
                               emp = emp,
                               events = events
                           }).AsEnumerable().Select(c => c.ToExpando())


            };

            return View(model);

        }
       public string GetBaseUrl()
       {

           return Request.Url.Scheme + "://" + Request.Url.Host + ":" + Request.Url.Port;
       }

       #region Single PayPal Payment
       public ActionResult CreatePayment(float amount)
       {
           var payment = PayPalPaymentService.CreatePayment(GetBaseUrl(), "sale", amount);

           return Redirect(payment.GetApprovalUrl());
       }

       public ActionResult PaymentCancelled()
       {
           // TODO: Handle cancelled payment
           return RedirectToAction("Error");
       }

       public ActionResult PaymentSuccessful(string paymentId, string token, string PayerID)
       {
           int eventid = Convert.ToInt32(Session["EventId"]);
           EventAd even_t = db.EventAds.Where(u => u.Id == eventid).SingleOrDefault();
           even_t.isPaid = 1;
           db.Entry(even_t).State = EntityState.Modified;
           db.SaveChanges();
           // Execute Payment
           var payment = PayPalPaymentService.ExecutePayment(paymentId, PayerID);
           return RedirectToAction("ThanksPage", "Jobs");
           //return View();
       }
       #endregion

       #region Authorize PayPal Payment
       public ActionResult AuthorizePayment()
       {
           var payment = PayPalPaymentService.CreatePayment(GetBaseUrl(), "authorize");

           return Redirect(payment.GetApprovalUrl());
       }

       public ActionResult AuthorizeSuccessful(string paymentId, string token, string PayerID)
       {
           // Capture Payment
           var capture = PayPalPaymentService.CapturePayment(paymentId);

           return View();
       }
       #endregion

       public ActionResult ManageEvents()
        {
            var currentDate = DateTime.Now.Date;
            if (User.Identity.IsAuthenticated)
            {
                var usrid = System.Web.HttpContext.Current.User.Identity.GetUserId();

                var usr = db.Users.Find(usrid);
                var user = db.Users.Where(u => u.Id == usr.Id).SingleOrDefault();
                if (user.UserType == "Administrator")
                {
                    var model = new ManageEventsViewModel
                    {
                        eventads= db.EventAds.OrderBy(u => u.EventDate >= currentDate).ToList()

                    };

                    return View(model);
                }
                else
                {
                   
                    var model = new ManageEventsViewModel
                    {
                        eventads = db.EventAds.Where(u => u.UserId == usr.Id).ToList()

                };
                    return View(model);
                }

            }
            return RedirectToAction("ClearLogin", "Account");

        }

        // GET: EventAds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventAd eventAd = db.EventAds.Find(id);
            if (eventAd == null)
            {
                return HttpNotFound();
            }
            return View(eventAd);
        }

        // GET: EventAds/Create
        public ActionResult Create(string UserId)
        {
            var currentDate = DateTime.Now.Date;
            ViewBag.eventCatagory = db.Eventcategories.ToList();
            var model = new EventAdViewsModel
            {
               // jobList = db.Jobs.OrderBy(u => u.CreatedDate).Take(10).ToList(),
                eventAdList = db.EventAds.OrderBy(u => u.EventDate >=currentDate).Take(6).ToList(),
                EventRate=   db.EventRates.ToList()[0].Amount,
                 
                       

            };
                return View(model);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create (EventAdViewsModel vm)
        {
            Decimal? Amount = 0;
            int jobid = 0;
            Session["Type"] = "EVENT";
            if (User.Identity.IsAuthenticated)
            {
                if (ModelState.IsValid)
                {
                    var usrid = System.Web.HttpContext.Current.User.Identity.GetUserId();

                    var usr = db.Users.Find(usrid);
                    vm.eventad.UserId = usr.Id;

                    var catId = vm.eventad.EventCategoryId;
                   
                    var catName = db.Eventcategories.Where(x => x.Id == catId).Select(x => x.Name).FirstOrDefault().ToString();
                    vm.eventad.EventNumber= DateTime.Now.ToString("MM") + DateTime.Now.Year.ToString().Substring(2, 2) + catName.Substring(0, 3).ToUpper() + db.EventAds.Max(x => x.Id);

                    var eventrate = db.EventRates.ToList();
                    float rate = 0;
                    if (eventrate != null)
                        rate = eventrate[0].Amount;

                    var coupon = db.EventCoupons.Where(x => x.CouponName == vm.CouponName && x.Status == 1 && x.Deleted == 0).FirstOrDefault();
                    if (coupon != null)
                    {
                        vm.eventad.EventAmount = Convert.ToDecimal((rate - coupon.Amount));
                    }
                    else
                        vm.eventad.EventAmount = Convert.ToDecimal(rate);
                    Amount = vm.eventad.EventAmount;
                    vm.eventad.EventAmount = Amount;
                    vm.eventad.status = false;
                    db.EventAds.Add(vm.eventad);
                    db.SaveChanges();
                    Session["EventId"] = vm.eventad.Id;
                    jcemail.EventPostedEmail(usr.Email, usr.FirstName + " " + usr.LastName, Url.Action("ClearLogin", "Account"));
                    jcemail.SendEmailToAdminEvent(usr.FirstName + " " + usr.LastName, usr.Email);
   
                }
               
                return RedirectToAction("CreatePayment", "Jobs", new { amount = Amount });
            }
            else {
                string userID = "";
                if (ModelState.IsValid)
                {
                    
                        ApplicationUser user = new ApplicationUser();

                        user.FirstName = vm.user.FirstName;
                        user.LastName = vm.user.LastName;
                        user.Email = vm.UserEmail;
                        user.UserName = vm.UserEmail;
                        user.PhoneNumber = vm.user.PhoneNumber;
                        string Password = vm.user.FirstName + "A@678";
                        user.UserType = "Employer";
                        var result = UserManager.CreateAsync(user, Password);

                        userID = user.Id;
                    
                    vm.eventad.UserId = userID;
                    vm.eventad.status = false;
                    var catId = vm.eventad.EventCategoryId;
                    var catName = db.Eventcategories.Where(x => x.Id == catId).Select(x => x.Name).FirstOrDefault().ToString();
                    vm.eventad.EventNumber = DateTime.Now.ToString("MM") + DateTime.Now.Year.ToString().Substring(2, 2) + catName.Substring(0, 3).ToUpper() + db.EventAds.Max(x => x.Id);
                    var eventrate = db.EventRates.ToList();
                    float rate = 0;
                    if (eventrate != null)
                        rate = eventrate[0].Amount;

                    var coupon = db.EventCoupons.Where(x => x.CouponName == vm.CouponName && x.Status == 1 && x.Deleted == 0).FirstOrDefault();
                    if (coupon != null)
                    {
                        vm.eventad.EventAmount = Convert.ToDecimal((rate - coupon.Amount));
                    }
                    else
                        vm.eventad.EventAmount = Convert.ToDecimal(rate);
                    Amount = vm.eventad.EventAmount;
                    vm.eventad.EventAmount = Amount;
                    db.EventAds.Add(vm.eventad);
                    db.SaveChanges();
                    Session["EventId"] = vm.eventad.Id;
                    jcemail.EmailPasswordToNewUserEvent(vm.UserEmail, vm.user.FirstName + " " + vm.user.LastName, Url.Action("ClearLogin", "Account"), Password);
                    jcemail.SendEmailToAdminEvent(vm.user.FirstName + " " + vm.user.LastName,vm.UserEmail);

                }
                return RedirectToAction("CreatePayment", "Jobs", new { amount = Amount });
            }
           
        }

        // GET: EventAds/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.eventCatagory = db.Eventcategories.ToList();
            if (User.Identity.IsAuthenticated)
            {

HealthCareJC/Views/EventAds/AllEvents.cshtml
@model IEnumerable<HealthCareJC.Models.EventAd>
@{
    ViewBag.Title = "AllEvents";
}
<hr/>
<div class="container">
    <div class="row">
        <div>
            <h3 class="margin-bottom-5">Events</h3>
            <div class="clearfix"></div>
            <table id="showdata" class="table dataTables-example">
                <thead style="display: none">
                    <tr>
                        <th></th>
                        
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Any())
            {
                <tr>
                    <td>
                        <div id="job-spotlight" class="showbiz-container">
                            <div>
                                <div>

                                    <ul>
                                        @foreach (var item in Model)
                                {
                                        

                                        <li>
                                            <div class="job-spotlight">
                                                <a href="@Url.Action("AllEvents","EventAds")">
                                                    <h4>
                                                        @item.Title<span class="part-time">
                                                            @item.EventDate.ToShortDateString()

                                                        </span> <span class="full-time">@item.time</span>
                                                    </h4>
                                                    <span><i class="fa fa-briefcase"></i>@item.eventCatrgory.Name</span>
                                                    <span><i class="fa fa-map-marker"></i>@item.Address</span>
                                                    <span><i class="fa fa-money"></i>@item.City</span>
                                                    <span><i class="fa fa-location-arrow"></i>@item.Zipcode</span>
                                                    <p>@item.Description</p>
                                                </a>
                                            </div>
                                        </li>

                                }

                                    </ul>

                                    <div class="clearfix"></div>

                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </td>
                </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
    <script>

        $(document).ready(function () {

            $('.dataTables-example').DataTable({

                "searching": false,
                "ordering": false,
                "pageLength": 10,
                "bLengthChange": false,
                "stateSave": true,
                "info": false
                //  "bPaginate": false

            });

        });






    </script>

HealthCareJC/Views/EventAds/Delete.cshtml
@model HealthCareJC.Models.EventAd

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventAd</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventCategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HealthCareJC/Views/EventAds/EventDetail.cshtml
@model HealthCareJC.ViewModels.EventAdViewsModel

<body>
    <hr />

    @{
        if (Model.eventlist != null)
        {
            foreach (var item in Model.eventlist)
            {



                <div id="wrapper">

                    <div class="container">

                        <!-- Recent Jobs -->
                        <div class="row">
                            <div class="col-md-8">

                                <!-- Company Info -->
                                <div class="company-info">
                                    <img src="~/Content/Images/Logo/@item.emp.Logo" alt="">
                                    <div class="content">
                                        <h3 style="color: green">@item.emp.CompanyName</h3>
                                        <span><i class="fa fa-building"></i>@item.emp.CompanyAddress</span>
                                        <span><i class="fa fa-arrow-right"></i>@item.emp.CompanyContactNo</span>
                                        <span><i class="fa fa-medkit"></i>@item.emp.CompanyEmail</span>

                                    </div>
                                    <div class="clearfix"></div>
                                </div>

                            </div>


                            <div class="col-lg-4">

                                <div class="margin-top-10">
                                    <div class="widget">
                                        <h4>Overview</h4>

                                        <div class="job-overview">

                                            <ul>
                                                <li>
                                                    <i class="fa fa-list"></i>
                                                    <div>
                                                        <strong>Title:</strong>
                                                        <span>@item.events.Title</span>
                                                    </div>
                                                </li>

                                                <li>
                                                    <i class="fa fa-map-marker"></i>
                                                    <div>
                                                        <strong>Address:</strong>
                                                        <span>@item.events.Address</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <i class="fa fa-user"></i>
                                                    <div>
                                                        <strong>Time:</strong>
                                                        <span>@item.events.time</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <i class="fa fa-user"></i>
                                                   
                                                    <div>
                                                        <strong>Event Date:</strong>
                                                        <span>@item.events.EventDate.ToShortDateString()</span>
                                                    </div>
                                                </li>
                                                <li>
                                                    <i class="fa fa-user"></i>
                                                    <div>
                                                        <strong>ContactPhone:</strong>
                                                        <span>@item.events.ContactPhone</span>
                                                    </div>
                                                </li>

 <li>
                                                    <i class="fa fa-user"></i>
                                                    <div>
                                                        <strong>Status</strong>
                                                        <span>
@if (item.events.status)
{
    <b style="color:dodgerblue">Approved</b>         <a href="@Url.Action("disApprove", "EventAds")?id=@item.events.Id"><i class="fa fa-pencil"></i> DisApprove</a>
}
else
{

    <b style="color:dodgerblue">Not Approved</b>        <a href="@Url.Action("PublishEvent", "EventAds")?id=@item.events.Id"><i class="fa fa-pencil"></i> Approve</a>
                                        }</span>
                                                    </div>
                                                </li>



                                            </ul>








                                        </div>

                                    </div>
                                </div>
                            </div>
                            <!-- Widgets / End -->

                        </div>
                    </div>


                </div>
            }

        }
    }
</body>

HealthCareJC/Views/EventAds/ManageEvents.cshtml
@model HealthCareJC.ViewModels.ManageEventsViewModel
@using HealthCareJC.Models;
@using Microsoft.AspNet.Identity;
@{


    ViewBag.Title = "ManageEvents";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
        ApplicationDbContext db = new ApplicationDbContext();

        var usrid = System.Web.HttpContext.Current.User.Identity.GetUserId();

        var usr = db.Users.Find(usrid);
        var obj = db.Users.Where(u => u.Id == usr.Id).SingleOrDefault();
    
}


<body>
    <div id="wrapper">
        <div class="clearfix"></div>
        
        <hr/>

        <div class="container">
            <div class="row">
                <h2>Manage Events</h2>
                @if (obj.UserType == "Employer")
                {
                    <nav id="breadcrumbs">
                        <ul>

                            <li>

                                <a href="@Url.Action("ManageJobs", "Jobs")" class="btn btn-success" style="color: white">Manage Jobs</a>
                            </li>
                            <li>

                                <a href="@Url.Action("EditEmployeerProfile", "Jobs")?userid=@obj.Id" class="btn btn-warning" style="color: white">My Profile</a>
                            </li>
                            <li>
                                <a href="@Url.Action("ForgotPassword","Account")" class="btn btn-info" style="color: white">Change Password</a>
                            </li>

                            <li><a href="@Url.Action("PostJob", "Jobs")" class="btn btn-primary" style="color: white"> Post New Job </a></li>

                            <li><a href="@Url.Action("Create", "EventAds")" class="btn btn-success" style="color: white"> Post New Event </a></li>
                            <li>
                                <a href="@Url.Action("ClearLogin", "Account")" class="btn btn-link">Log Out</a>
                            </li>
                        </ul>
                    </nav>
                }
                else if (obj.UserType == "Administrator")
                {
                    <nav id="breadcrumbs">
                        <ul>



                            <li style="margin-bottom: 10px">

                                <a href="@Url.Action("ManageJobs", "Jobs")" class="btn btn-success" style="color: white">Manage Jobs</a>
                            </li>
                            <li style="margin-bottom: 10px"><a href="@Url.Action("Index","Employers")" class="btn btn-info" style="color: white"> Manage Employers </a></li>
                            <li style="margin-bottom: 10px">

                                <a href="#" class="btn btn-info" style="color: white">Manage Job Seekers</a>
                            </li>
                            <li style="margin-bottom: 10px">

                                <a href="@Url.Action("JobCategoriesList", "JobCategories")" class="btn btn-primary" style="color: white">Manage Job Categories</a>
                            </li>
                            <li style="margin-bottom: 10px">

                                <a href="@Url.Action("Index", "Specialities")" class="btn btn-success" style="color: white"> Manage Job Specialities</a>
                            </li>
                            <li style="margin-bottom: 10px">

                                <a href="@Url.Action("Index", "EventCategories")" class="btn btn-warning" style="color: white"> Manage Event Categories</a>
                            </li>
                            <li style="margin-bottom: 10px">
                                <a href="@Url.Action("ClearLogin","Account")" class="btn btn-link">Log Out</a>
                            </li>


                        </ul>

                    </nav>
                }
                else
                {
                    <nav id="breadcrumbs">

                        <ul>
                            <li style="margin-bottom: 10px"><a href="@Url.Action("AppliedJobs","Resumes")?id=@obj.Id" class="btn btn-primary" style="color: white"> Applied Jobs </a></li>
                            <li style="margin-bottom: 10px">
                                <a href="@Url.Action("EditResume","Resumes")?UserID=@obj.Id" class="btn btn-info" style="color: white">My Profile</a>
                            </li>
                            <li style="margin-bottom: 10px">
                                <a href="@Url.Action("ResumeDetail","Resumes")?id=@obj.Id" class="btn btn-warning" style="color: white">My Resume</a>
                            </li>
                            <li style="margin-bottom: 10px">
                                <a href="@Url.Action("ForgotPassword","Account")" class="btn btn-danger" style="color: white">Change Password</a>
                            </li>
                            <li style="margin-bottom: 10px">
                                <a href="@Url.Action("ClearLogin", "Account")">Log Out</a>
                            </li>


                        </ul>

                    </nav>
                }

            </div>
            <!-- Table -->
            <div class="row">

                <p class="margin-bottom-25">Your listings are shown in the table below. Expired listings will be automatically removed after 30 days.</p>

                <table class="manage-table responsive-table">
                    <thead>
                    <tr>
                        <th><i class="fa fa-file-text"></i> Title</th>
                        <th><i class="fa fa-calendar"></i>Status</th>
                        <th><i class="fa fa-calendar"></i> Event Address</th>
                        <th><i class="fa fa-calendar"></i> Date</th>

                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (Model.eventads.Any())
                    {
                        foreach (var item in Model.eventads)
                        {
                           





                            <tr>
                                <td class="title"><a href="#">@item.Title</a></td>
                                @if (item.status)
                                {
                                <td class="title">Approved</td>
                                }
                                else
                                {
                                    <td class="title">Un Approved</td>
                                }
                                <td>@item.Address</td>
                                <td>@item.EventDate.ToShortDateString()</td>
                                <td class="action">
                                  
                                   
                                    @if (usr.UserType == "Administrator")
                                    {
                                        if (item.status)
                                        {
                                            <a href="@Url.Action("disApprove", "EventAds")?id=@item.Id"><i class="fa fa-pencil"></i> DisApprove</a>
                                        }
                                        else
                                        {

                                            <a href="@Url.Action("PublishEvent", "EventAds")?id=@item.Id"><i class="fa fa-pencil"></i> Approve</a>
                                        }
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Edit","EventAds")?id=@item.Id"><i class="fa  fa-pencil "></i>Edit</a>
                                        }
                                    <a href="@Url.Action("EventDetail","EventAds")?eventId=@item.Id" class="delete"><i class="fa fa-dashboard"></i> Details</a>

                                    <a href="@Url.Action("DeleteConfirmed","EventAds")" class="delete"><i class="fa fa-remove"></i> Delete</a>

                                </td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>

                <br>
                @*<a href="@Url.Action("Create","EventAds")" class="button">Add event</a>*@

            </div>

        </div>



        <div class="margin-top-60"></div>



    </div>


</body>
<script>
    $(document).ready(function () {

        $('.manage-table').DataTable({
            "searching": false,
            "ordering": false,
            "pageLength": 10,
            "stateSave": true,
            "bLengthChange": false,
            "info": false,
            
        });


    });
</script>