HealthCareJC/Models/Subscriber.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HealthCareJC.Models
{
    public class Subscriber
    {
        public int Id { get; set; }
        [Required]
        public string FullName { get; set; }

        [Required]
        public string Email { get; set; }

        public string Phone { get; set; }

        public bool Active { get; set; }
    }
}

HealthCareJC/Controllers/SubscribersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HealthCareJC.Models;
using HealthCareJC.Services;

namespace HealthCareJC.Controllers
{
    public class SubscribersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Subscribers
        public ActionResult AddSubscriber(FormCollection frmCollection)
        {
            Subscriber subscriber=new Subscriber();
            subscriber.FullName= frmCollection["fullname"].ToString();
            subscriber.Email = frmCollection["email"].ToString();
            subscriber.Phone = frmCollection["phone"].ToString();
            subscriber.Active = true;

            db.Subscribers.Add(subscriber);
            db.SaveChanges();
     
            JCEmailService emailService= new JCEmailService();
            emailService.SendEmailToSubscriber(subscriber.Email,subscriber.FullName);

            if (subscriber.Phone != null || subscriber.Phone != "")
            {
                JCSmsService smsService= new JCSmsService();
                smsService.SendSmsToSubscriber(subscriber.Phone,subscriber.FullName);
            }

            return RedirectToAction("ThanksSubscriber");
        }
       
        public ActionResult ThanksSubscriber()
        {
            return View();
        }
    }
}

HealthCareJC/Views/Subscribers/ThanksSubscriber.cshtml
<hr/>
<div id="wrapper">
    <br/>
    <br/>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            
            <span class="centered">
                <center>  <h2>Subscribed Successfully</h2></center>
            </span>

            <h4>Thank you for you interest in HeathCare Job Search Center! Keep checking your Inbox for latest News, Updates, Job Alerts and many more... </h4>

            <center>   @Html.ActionLink("Continue Using System", "Index", "Home", new { @class = "btn btn-Primary" }, null)</center>


        </div>

    </div>

</div>



<div class="clearfix"></div>
<div class="margin-top-30"></div>


<div class="margin-bottom-50"></div>

HealthCareJC/Views/Subscribers/_Subscriber.cshtml
<div class="modal inmodal" id="searchModal" tabindex="-1" role="dialog" aria-hidden="true" style="margin-top: 50px">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>

                <h5 class="modal-title" style="color: #ed5565">Get Alerts & Update In Your Inbox</h5>

            </div>
            @using (Html.BeginForm(Html.BeginForm("AddSubscriber", "Subscribers", FormMethod.Post)))
            {
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        
                        <div class="small-dialog-content">

                            <input type="text" name="fullname" placeholder="Full Name" value="" required="" />
                            <input type="email" name="email" placeholder="Email Address" value="" required="" />
                            <input type="text" name="phone" placeholder="Contact Number" value="" />

                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" id="submit" value="Subscribe" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>