HealthCareJC/Models/Speciality.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HealthCareJC.Models
{
    public class Speciality
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

HealthCareJC/Controllers/SpecialitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthCareJC.Models;

namespace HealthCareJC.Controllers
{
    public class SpecialitiesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Specialities
        public ActionResult Index()
        {
            return View(db.specialities.ToList());
        }

        // GET: Specialities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Speciality speciality = db.specialities.Find(id);
            if (speciality == null)
            {
                return HttpNotFound();
            }
            return View(speciality);
        }

        // GET: Specialities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Specialities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Speciality speciality)
        {
            if (ModelState.IsValid)
            {
                db.specialities.Add(speciality);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(speciality);
        }

        // GET: Specialities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Speciality speciality = db.specialities.Find(id);
            if (speciality == null)
            {
                return HttpNotFound();
            }
            return View(speciality);
        }

        // POST: Specialities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Speciality speciality)
        {
            if (ModelState.IsValid)
            {
                db.Entry(speciality).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(speciality);
        }

        // GET: Specialities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Speciality speciality = db.specialities.Find(id);
            if (speciality == null)
            {
                return HttpNotFound();
            }
            return View(speciality);
        }

        // POST: Specialities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Speciality speciality = db.specialities.Find(id);
            db.specialities.Remove(speciality);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HealthCareJC/Views/Specialities/Create.cshtml
@model HealthCareJC.Models.Speciality

@{
   
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create </title>
</head>
<body>

    <div id="wrapper">
        <div class="row">


            <div class="container">
                <hr />
                <h4>Create New Specialty</h4>
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>


</body>
</html>

HealthCareJC/Views/Specialities/Delete.cshtml
@model HealthCareJC.Models.Speciality

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Speciality</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

HealthCareJC/Views/Specialities/Details.cshtml
@model HealthCareJC.Models.Speciality

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Speciality</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

HealthCareJC/Views/Specialities/Edit.cshtml
@model HealthCareJC.Models.Speciality

@{
    
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit </title>
</head>
<body>

    <div id="wrapper">
        <div class="row">


            <div class="container">
                <hr />
                <h4>Edit Specialty</h4>
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>


</body>
</html>

HealthCareJC/Views/Specialities/Index.cshtml
@using HealthCareJC.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<HealthCareJC.Models.Speciality>

@{
    ApplicationDbContext db = new ApplicationDbContext();

    var usrid = System.Web.HttpContext.Current.User.Identity.GetUserId();

    var usr = db.Users.Find(usrid);
    var obj = db.Users.Where(u => u.Id == usr.Id).SingleOrDefault();
}

<hr />

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <div id="wrapper">
        <div class="row">


            <div class="container">
                <div class="row">
                    @if (obj.UserType == "Administrator")
                    {
                        <nav id="breadcrumbs">
                            <ul>


                                <li style="margin-bottom: 10px">

                                    <a href="@Url.Action("ManageJobs", "Jobs")" class="btn btn-success" style="color: white">Manage Jobs</a>
                                </li>
                                <li style="margin-bottom: 10px">
                                    <a href="@Url.Action("ManageEvents", "Eventads")" class="btn btn-success" style="color: white">Manage Event Ads</a>
                                </li>
                                <li style="margin-bottom: 10px"><a href="@Url.Action("Index","Employers")" class="btn btn-info" style="color: white"> Manage Employers </a></li>
                                <li style="margin-bottom: 10px">

                                    <a href="#" class="btn btn-info" style="color: white">Manage Job Seekers</a>
                                </li>
                                <li style="margin-bottom: 10px">

                                    <a href="@Url.Action("JobCategoriesList", "JobCategories")" class="btn btn-primary" style="color: white">Manage Job Categories</a>
                                </li>
                                <li style="margin-bottom: 10px">

                                    <a href="@Url.Action("Index", "Specialities")" class="btn btn-success" style="color: white"> Manage Job Specialities</a>
                                </li>
                                <li style="margin-bottom: 10px">

                                    <a href="@Url.Action("Index", "EventCategories")" class="btn btn-warning" style="color: white"> Manage Event Categories</a>
                                </li>
                                <li style="margin-bottom: 10px">
                                    <a href="@Url.Action("ClearLogin","Account")" class="btn btn-link">Log Out</a>
                                </li>


                            </ul>

                        </nav>
                    }


                </div>
                <hr/>
                <span class="pull-left">
                    <h3>Job Specialties</h3></span>
                <span class="pull-right">
                    <p>
                        @Html.ActionLink("Create New", "Create", new {@class = "btn btn-primary"})
                    </p>
                </span>

                <table class="table">
                    @*<tr>
                        <th>
                            Specialty Name
                        </th>
                        <th></th>
                    </tr>*@

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) @*|*@

                                @*@Html.ActionLink("Delete", "Delete", new {id = item.Id})*@
                            </td>
                        </tr>
                    }

                </table>

            </div>
        </div>
    </div>
</body>
</html>